// Generated by https://quicktype.io
class Contratistas {
  List<Contratista> items = [];

  Contratistas();

  Contratistas.fromJsonList(List<dynamic> jsonlist) {
    for (var item in jsonlist) {
      final contratista = new Contratista.fromJsonMap(item);
      items.add(contratista);
    }
  }
}

class Contratista {
  String? id;
  String? correo;
  String? rol;
  String? nombre;
  String? apellido;

  Contratista(
      {this.id,
      this.correo,
      this.rol,
      this.nombre,
      this.apellido,});

  Contratista.fromJsonMap(Map<String, dynamic> json) {
    id = json['id'];
    correo = json['correo'];
    rol = json['rol'];
    nombre = json['nombre'];
    apellido = json['apellido'];
  }
}
